baseURL: 'https://skozar.github.io/iToraChats/'
languageCode: 'en-us'
title: 'iTORA Project'
theme: 'bs5'
params:
  description: "iTORA chats history 2021/2022"
enableRobotsTXT: true
publishdir: 'docs'
